Repository FRCTeam3255/Robot2023, pull requests merged in 2023-02, with the labels that each got.

#183 practice bot tuning, safety, and control fixes
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/RobotPreferences.java
  src/main/java/frc/robot/commands/MoveArm.java
  src/main/java/frc/robot/subsystems/Arm.java
  src/main/java/frc/robot/subsystems/Collector.java
Labels: tested

#194 Create prep placement command
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/commands/PrepPlacement.java
  src/main/java/frc/robot/subsystems/Arm.java
Labels: tested

#199 intake cube command
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/RobotPreferences.java
  src/main/java/frc/robot/commands/IntakeCube.java
  src/main/java/frc/robot/subsystems/Arm.java
Labels: tested

#198 Simplified PrepPlacement & PlaceGamePiece
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/RobotPreferences.java
  src/main/java/frc/robot/commands/PlaceGamePiece.java
  src/main/java/frc/robot/commands/PrepPlacement.java
  src/main/java/frc/robot/subsystems/Arm.java
  src/main/java/frc/robot/subsystems/Intake.java
Labels: tested

#204 Defense mode
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/SN_SwerveModule.java
  src/main/java/frc/robot/subsystems/Drivetrain.java
Labels: tested

#216 improved intake cone command
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/RobotMap.java
  src/main/java/frc/robot/RobotPreferences.java
  src/main/java/frc/robot/commands/IntakeCone.java
Labels: tested

#221 QA into Main - 2/23/23 Tested
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/RobotMap.java
  src/main/java/frc/robot/RobotPreferences.java
  src/main/java/frc/robot/SN_SwerveModule.java
  src/main/java/frc/robot/commands/Dock.java
  src/main/java/frc/robot/commands/Drive.java
  src/main/java/frc/robot/commands/IntakeCone.java
  src/main/java/frc/robot/commands/IntakeCube.java
  src/main/java/frc/robot/commands/MoveArm.java
  src/main/java/frc/robot/commands/PlaceGamePiece.java
  src/main/java/frc/robot/commands/PrepPlacement.java
  src/main/java/frc/robot/subsystems/Arm.java
  src/main/java/frc/robot/subsystems/Drivetrain.java
  src/main/java/frc/robot/subsystems/Intake.java
  src/main/java/frc/robot/subsystems/Vision.java
  vendordeps/PathplannerLib.json
  vendordeps/Phoenix.json
  vendordeps/SuperCORE.json
  vendordeps/photonlib.json
Labels: tested

#220 replace pose estimation rotation with raw navx yaw
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/subsystems/Drivetrain.java
Labels: tested, High Priority

#180 Drivetrain angle alignment snapping
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/RobotPreferences.java
  src/main/java/frc/robot/commands/Drive.java
  src/main/java/frc/robot/subsystems/Drivetrain.java
Labels: robot required, tested, High Priority

#214 change reset to absolute functionality
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/subsystems/Collector.java
  src/main/java/frc/robot/subsystems/Drivetrain.java
Labels: robot required, tested, High Priority

#218 clarify preference naming and add comments
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/RobotPreferences.java
  src/main/java/frc/robot/subsystems/Arm.java
Labels: tested, low priority

#222 delete charger subsystem
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/RobotMap.java
  src/main/java/frc/robot/RobotPreferences.java
  src/main/java/frc/robot/subsystems/Charger.java
Labels: tested

#210 switch to falcon pid for arm
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/RobotPreferences.java
  src/main/java/frc/robot/commands/MoveArm.java
  src/main/java/frc/robot/subsystems/Arm.java
Labels: robot required, tested, Mid Priority

#235 changed elbow angles in arm stow and cone preferences
  src/main/java/frc/robot/RobotPreferences.java
Labels: tested
