Repository FRCTeam3255/Robot2023, pull requests merged in 2023-03, with the labels that each got.

#240 Fix offsets on practice bot
  src/main/java/frc/robot/Constants.java
Labels: tested

#248 switch intake switch to dio from spark max
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotMap.java
  src/main/java/frc/robot/subsystems/Intake.java
Labels: tested

#247 changed operator controls
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/subsystems/Arm.java
Labels: tested

#251 add camera
  src/main/java/frc/robot/Robot.java
Labels: tested

#254 Offsets and deadbands
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/subsystems/Drivetrain.java
Labels: tested

#269 removed stale todo comments
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/RobotPreferences.java
Labels: no functional change

#271 rename dock command to engage
  src/main/java/frc/robot/commands/Engage.java
Labels: no functional change

#285 swoffsets @ home
  src/main/java/frc/robot/Constants.java
Labels: tested

#270 completely delete color sensor
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotMap.java
  src/main/java/frc/robot/RobotPreferences.java
  src/main/java/frc/robot/subsystems/Intake.java
Labels: tested, no functional change

#272 removed (nonfunctional) drivetrain snapping prevention while shoulder is up
  src/main/java/frc/robot/commands/Drive.java
Labels: tested

#276 rewrite numpad input logic
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/commands/Auto/CubeConeDock.java
  src/main/java/frc/robot/commands/PlaceGamePiece.java
  src/main/java/frc/robot/commands/SetLEDs.java
  src/main/java/frc/robot/subsystems/Arm.java
Labels: tested

#287 Uncommented addVisionMeasurement
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/RobotPreferences.java
  src/main/java/frc/robot/commands/AddVisionMeasurement.java
  src/main/java/frc/robot/subsystems/Drivetrain.java
  src/main/java/frc/robot/subsystems/Vision.java
Labels: tested

#284 rewrite the arm
  src/main/deploy/pathplanner/bigL.path
  src/main/deploy/pathplanner/bottomConeThenDock.path
  src/main/deploy/pathplanner/cubeThenStagingMark.path
  src/main/deploy/pathplanner/prepThenBottomCone.path
  src/main/deploy/pathplanner/stagingMarkThenDock.path
  src/main/deploy/pathplanner/stagingMarkThenPrep.path
  src/main/deploy/pathplanner/toStagingMark.path
  src/main/deploy/pathplanner/twoConePath.path
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/commands/Auto/CubeConeDock.java
  src/main/java/frc/robot/commands/Auto/CubeDockShoot.java
  src/main/java/frc/robot/commands/Auto/OnePiece/CenterCube.java
  src/main/java/frc/robot/commands/Auto/OnePiece/CubeThenDock.java
  src/main/java/frc/robot/commands/Auto/OnePiece/CubeThenMobilityCable.java
  src/main/java/frc/robot/commands/Auto/OnePiece/CubeThenMobilityOpen.java
  src/main/java/frc/robot/commands/IntakeCone.java
  src/main/java/frc/robot/commands/IntakeCube.java
  src/main/java/frc/robot/commands/IntakeFloor.java
  src/main/java/frc/robot/commands/MoveArm.java
  src/main/java/frc/robot/commands/PlaceGamePiece.java
  src/main/java/frc/robot/commands/SetLEDs.java
  src/main/java/frc/robot/subsystems/Arm.java
  src/main/java/frc/robot/subsystems/Drivetrain.java
Labels: tested

#295 changed how isDriveOpenLoop is used
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/commands/Drive.java
  src/main/java/frc/robot/commands/Engage.java
  src/main/java/frc/robot/subsystems/Drivetrain.java
Labels: tested

#293 Motion magic
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/RobotPreferences.java
  src/main/java/frc/robot/subsystems/Arm.java
Labels: tested

#291 Added LEDs and rumble for driver feedback
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/RobotPreferences.java
  src/main/java/frc/robot/commands/SetLEDs.java
  src/main/java/frc/robot/commands/SetRumble.java
  src/main/java/frc/robot/subsystems/Intake.java
Labels: tested

#297 added leds when centered on charge station
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/RobotPreferences.java
  src/main/java/frc/robot/commands/SetLEDs.java
Labels: tested

#300 New arm changes
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/commands/Drive.java
Labels: tested

#301 tuned motion magic values
  src/main/java/frc/robot/RobotPreferences.java
Labels: tested

#303 Added y coordinate to charge station center
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotPreferences.java
  src/main/java/frc/robot/commands/SetLEDs.java
Labels: tested

#312 added LEDs for column alignment
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/RobotPreferences.java
  src/main/java/frc/robot/commands/SetLEDs.java
  src/main/java/frc/robot/subsystems/Arm.java
  src/main/java/frc/robot/subsystems/Drivetrain.java
Labels: tested

#306 added new collector
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/RobotMap.java
  src/main/java/frc/robot/RobotPreferences.java
  src/main/java/frc/robot/commands/IntakeCubeDeploy.java
  src/main/java/frc/robot/commands/IntakeCubeRetract.java
  src/main/java/frc/robot/commands/MoveArm.java
  src/main/java/frc/robot/commands/PivotCollector.java
  src/main/java/frc/robot/subsystems/Arm.java
  src/main/java/frc/robot/subsystems/Collector.java
Labels: tested

#305 Switch to shuffleboard
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/subsystems/Arm.java
  src/main/java/frc/robot/subsystems/Drivetrain.java
  src/main/java/frc/robot/subsystems/Intake.java
  src/main/java/frc/robot/subsystems/SuperShuffle.java
Labels: tested

#316 removed collector bindings (very important)
  src/main/java/frc/robot/RobotContainer.java
Labels: tested

#317 move up arm stow
  src/main/java/frc/robot/Constants.java
Labels: tested

#318 Arm stow at node
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/commands/PlaceGamePiece.java
  src/main/java/frc/robot/subsystems/Arm.java
Labels: tested

#323 Leds node alignment for red alliance
  src/main/java/frc/robot/RobotPreferences.java
  src/main/java/frc/robot/commands/SetLEDs.java
  src/main/java/frc/robot/subsystems/Drivetrain.java
Labels: tested

#322 collector roller on when ready and bind to reset encoderse on driver
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/commands/IntakeCubeDeploy.java
  src/main/java/frc/robot/commands/IntakeCubeRetract.java
  src/main/java/frc/robot/subsystems/Collector.java
Labels: tested
